Update azure-pipelines-1.yml for Azure Pipelines

diff --git a/azure-pipelines-1.yml b/azure-pipelines-1.yml
--- a/azure-pipelines-1.yml
+++ b/azure-pipelines-1.yml
@@ -35,6 +35,17 @@ stages:
           runOnce:
             deploy:
               steps:
+                - task: AzureCLI@2
+                  displayName: "Check if .dacpac file exists"
+                  inputs:
+                    azureSubscription: "vs-enterprise-mpn-miguel-swanepoel (5cb7ba0e-90a4-4d6d-b238-f361039dc222)"
+                    scriptType: "bash"
+                    scriptLocation: "inlineScript"
+                    inlineScript: |
+                      if [ ! -f "$(Pipeline.Workspace)/drop/ms-automation-sasol-pipeline-sqldb-dev.dacpac" ]; then
+                        echo "Error: .dacpac file not found. Aborting deployment."
+                        exit 1
+                      fi
                 - task: SqlAzureDacpacDeployment@1
                   inputs:
                     azureSubscription: "vs-enterprise-mpn-miguel-swanepoel (5cb7ba0e-90a4-4d6d-b238-f361039dc222)"
@@ -44,3 +55,4 @@ stages:
                     SqlPassword: "$(SqlPassword)"  # Store as a secret variable in the pipeline
                     DacpacFile: "$(Pipeline.Workspace)/drop/ms-automation-sasol-pipeline-sqldb-dev.dacpac"
                     DeployType: "DacpacTask"
+
